
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action QuitAction;

	private global::Gtk.Action HelpAction1;

	private global::Gtk.Action AboutAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button btn_clear;

	private global::Gtk.Button btn_write;

	private global::Gtk.Button btn_quit;

	private global::Gtk.CheckButton chkBx_readOnly;

	private global::Gtk.CheckButton chkBx_printable;

	private global::Gtk.CheckButton chkBx_guests;

	private global::Gtk.CheckButton chkBx_browseable;

	private global::Gtk.Entry txtBx_shareName;

	private global::Gtk.Entry txtBx_desc;

	private global::Gtk.Entry txtbx_path;

	private global::Gtk.Entry txtBx_validUsers;

	private global::Gtk.Label label4;

	private global::Gtk.Label label2;

	private global::Gtk.Label label1;

	private global::Gtk.Button btn_userHelp;

	private global::Gtk.Label label3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.QuitAction = new global::Gtk.Action("QuitAction", global::Mono.Unix.Catalog.GetString("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quit");
		w1.Add(this.QuitAction, null);
		this.HelpAction1 = new global::Gtk.Action("HelpAction1", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction1, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Maxixie");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-yes", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='HelpAction1' action='HelpAction1'/><menuitem name='AboutAction' action='AboutAction'/></menu><menu><menuitem/></menu><menu><menuitem/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox2.Add(this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu><menuitem/></menu><menu><menuitem/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox2.Add(this.menubar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_clear = new global::Gtk.Button();
		this.btn_clear.CanFocus = true;
		this.btn_clear.Name = "btn_clear";
		this.btn_clear.UseUnderline = true;
		this.btn_clear.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.fixed1.Add(this.btn_clear);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_clear]));
		w4.X = 309;
		w4.Y = 188;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_write = new global::Gtk.Button();
		this.btn_write.CanFocus = true;
		this.btn_write.Name = "btn_write";
		this.btn_write.UseUnderline = true;
		this.btn_write.Label = global::Mono.Unix.Catalog.GetString("Write");
		this.fixed1.Add(this.btn_write);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_write]));
		w5.X = 309;
		w5.Y = 157;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_quit = new global::Gtk.Button();
		this.btn_quit.CanFocus = true;
		this.btn_quit.Name = "btn_quit";
		this.btn_quit.UseUnderline = true;
		this.btn_quit.Label = global::Mono.Unix.Catalog.GetString("Quit");
		this.fixed1.Add(this.btn_quit);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_quit]));
		w6.X = 348;
		w6.Y = 189;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkBx_readOnly = new global::Gtk.CheckButton();
		this.chkBx_readOnly.CanFocus = true;
		this.chkBx_readOnly.Name = "chkBx_readOnly";
		this.chkBx_readOnly.Label = global::Mono.Unix.Catalog.GetString("Read Only");
		this.chkBx_readOnly.DrawIndicator = true;
		this.chkBx_readOnly.UseUnderline = true;
		this.fixed1.Add(this.chkBx_readOnly);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkBx_readOnly]));
		w7.X = 9;
		w7.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkBx_printable = new global::Gtk.CheckButton();
		this.chkBx_printable.CanFocus = true;
		this.chkBx_printable.Name = "chkBx_printable";
		this.chkBx_printable.Label = global::Mono.Unix.Catalog.GetString("Printable");
		this.chkBx_printable.DrawIndicator = true;
		this.chkBx_printable.UseUnderline = true;
		this.fixed1.Add(this.chkBx_printable);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkBx_printable]));
		w8.X = 9;
		w8.Y = 33;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkBx_guests = new global::Gtk.CheckButton();
		this.chkBx_guests.CanFocus = true;
		this.chkBx_guests.Name = "chkBx_guests";
		this.chkBx_guests.Label = global::Mono.Unix.Catalog.GetString("Allow Guests");
		this.chkBx_guests.DrawIndicator = true;
		this.chkBx_guests.UseUnderline = true;
		this.fixed1.Add(this.chkBx_guests);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkBx_guests]));
		w9.X = 9;
		w9.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkBx_browseable = new global::Gtk.CheckButton();
		this.chkBx_browseable.CanFocus = true;
		this.chkBx_browseable.Name = "chkBx_browseable";
		this.chkBx_browseable.Label = global::Mono.Unix.Catalog.GetString("Browseable");
		this.chkBx_browseable.DrawIndicator = true;
		this.chkBx_browseable.UseUnderline = true;
		this.fixed1.Add(this.chkBx_browseable);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkBx_browseable]));
		w10.X = 9;
		w10.Y = 67;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtBx_shareName = new global::Gtk.Entry();
		this.txtBx_shareName.CanFocus = true;
		this.txtBx_shareName.Name = "txtBx_shareName";
		this.txtBx_shareName.IsEditable = true;
		this.txtBx_shareName.InvisibleChar = '●';
		this.fixed1.Add(this.txtBx_shareName);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBx_shareName]));
		w11.X = 215;
		w11.Y = 4;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtBx_desc = new global::Gtk.Entry();
		this.txtBx_desc.CanFocus = true;
		this.txtBx_desc.Name = "txtBx_desc";
		this.txtBx_desc.IsEditable = true;
		this.txtBx_desc.InvisibleChar = '●';
		this.fixed1.Add(this.txtBx_desc);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBx_desc]));
		w12.X = 216;
		w12.Y = 35;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtbx_path = new global::Gtk.Entry();
		this.txtbx_path.CanFocus = true;
		this.txtbx_path.Name = "txtbx_path";
		this.txtbx_path.IsEditable = true;
		this.txtbx_path.InvisibleChar = '●';
		this.fixed1.Add(this.txtbx_path);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtbx_path]));
		w13.X = 214;
		w13.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtBx_validUsers = new global::Gtk.Entry();
		this.txtBx_validUsers.CanFocus = true;
		this.txtBx_validUsers.Name = "txtBx_validUsers";
		this.txtBx_validUsers.IsEditable = true;
		this.txtBx_validUsers.InvisibleChar = '●';
		this.fixed1.Add(this.txtBx_validUsers);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBx_validUsers]));
		w14.X = 212;
		w14.Y = 103;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Share Name");
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w15.X = 142;
		w15.Y = 6;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Description");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w16.X = 146;
		w16.Y = 38;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Share Path");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w17.X = 143;
		w17.Y = 74;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_userHelp = new global::Gtk.Button();
		this.btn_userHelp.CanFocus = true;
		this.btn_userHelp.Name = "btn_userHelp";
		this.btn_userHelp.UseUnderline = true;
		this.btn_userHelp.Label = global::Mono.Unix.Catalog.GetString("?");
		this.fixed1.Add(this.btn_userHelp);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_userHelp]));
		w18.X = 196;
		w18.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Valid Users");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w19.X = 131;
		w19.Y = 107;
		this.vbox2.Add(this.fixed1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed1]));
		w20.Position = 2;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 293;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler(this.OnQuitActionActivated);
		this.HelpAction1.Activated += new global::System.EventHandler(this.OnHelpAction1Activated);
		this.AboutAction.Activated += new global::System.EventHandler(this.OnAboutActionActivated);
		this.btn_clear.Clicked += new global::System.EventHandler(this.OnBtnClearClicked);
		this.btn_write.Clicked += new global::System.EventHandler(this.OnBtnWriteClicked);
		this.btn_quit.Clicked += new global::System.EventHandler(this.OnBtnQuitClicked);
		this.btn_userHelp.Activated += new global::System.EventHandler(this.OnBtnUserHelpActivated);
	}
}
